# Generated by Django 5.1.1 on 2024-10-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_updated_at_alter_orderproduct_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_method',
            new_name='amount_paid',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='ammount_paid',
            new_name='payment_method',
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
